In [1]:
#텐서플로우 보다 더작은 단위(LLm:pytorch만 가능)
#파이토치 설치
!pip install torch torchvision torchaudio

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.6/80.6 MB 17.4 MB/s  0:00:04m0:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 18.4 MB/s  0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 679.9/679.9 kB 8.1 MB/s  0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 19.5 MB/s  0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 16.8 MB/s  0:00:00 eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB 13.9 MB/s  0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8/8 [torchvision] [torchvision]


-torch:pytorch의 핵심 패키지
-torchvision:컴퓨터 비전을 위한 데이터셋, 모델아키텍처, 이미지 변환등
-torchaudio:오디오 처리와 관련된 도구의 라이브러리

#Tensor
-머신러닝과 딥러닝에서 사용되는 기본적인 구조
-다차원 배열과 숫자데이터를 저장하고 조작하는데 사용

#Tensor의 특징
-다차원 배열:Tensor는 1차원(벡터), 2차원(행렬), 3차원이상의 다차원 데이터를 표현
-GPU 지원:Tensor는 GPU에서 연산을 수행할수 있어 빠른 계산이 가능
-자동 미분:Tensor는 자동 미분(AutoGrad) 기능을 지원하여 딥러닝 모델의 학습에 필요한 기울기 계산을 자동으로 수행한다.:기울기(sgb)
#gpu(메모리와 연결하지 않음. 메모리를 가지고 있음. 할당을 해줘야함)-cpu+memory/hard

In [ ]:
#Tensor의 생성
import torch

#1차원 Tensor 생성
t1=torch.tensor([1,2,3,4])
print(t1)#array아님,numpy보다 작은 단위

tensor([1, 2, 3, 4])


In [ ]:
#2차원 Tensor
t2=torch.tensor(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)
print(t2)#타입 텐서

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [4]:
#tensor크기 확인
print(t1.shape)
print(t2.shape)

torch.Size([4])
torch.Size([3, 3])


In [5]:
#Tensor의 타입 확인 및 변경
print(t1.dtype)
t1_float=t1.float()
print(t1_float.dtype)
print(t1_float)

torch.int64
torch.float32
tensor([1., 2., 3., 4.])


In [7]:
#TENSOR의 연산
a=torch.tensor([1,2,3])
b=torch.tensor([4,5,6])

print(a+b)
print(a*b)

tensor([5, 7, 9])
tensor([ 4, 10, 18])


In [9]:
#Tensor의 indexing과 slicing
t=torch.tensor(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)
print(t)
print(t[1,1])
print(t[:,1])
print(t[:,-1])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor(5)
tensor([2, 5, 8])
tensor([3, 6, 9])


In [ ]:
#Boolean Indexing
t1=torch.tensor([1,2,3,4,5])
t1>3#tensor([true/false])
t1[t1>3]#tensor([])

tensor([False, False, False,  True,  True])

In [14]:
#reshape,view 차원 변경
t=torch.tensor([1,2,3,4,5,6])
t_reshaped=t.reshape(2,3)
t_reshaped

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
#view
t_view=t.view(2,3)
t_view

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
###################
# Tensor의 차원변경:squeeze,unsqueeze

t=torch.tensor([1,2,3])
print(t)
print(t.shape)
print('-'*15)

t_unsqueezed=t.unsqueeze(0)#지정한 위치에 크기가 1인 차원을 추가
print(t_unsqueezed)#차원 추가:2차원
print(t_unsqueezed.shape)
print('-'*15)

t_unsqueezed_squeeze = t_unsqueezed.squeeze(0)#지정한 위치에 크기가 1인 차원을 제거(1인경우 제거 안됌??)
print(t_unsqueezed_squeeze)#차원 추가:2차원
print(t_unsqueezed_squeeze.shape)
print('-'*15)
#####################################

tensor([1, 2, 3])
torch.Size([3])
---------------
tensor([[1, 2, 3]])
torch.Size([1, 3])
---------------
tensor([1, 2, 3])
torch.Size([3])
---------------


In [27]:
#Ex:
x=torch.ones(2,1,2)
print(x)#페이지 로우 컬럼
print(x.shape)
print("-"*15)

#모든 크기가 1인 차원 제거
x_squeezed=x.squeeze()
print(x_squeezed)
print(x_squeezed.shape)
print("-"*15)

tensor([[[1., 1.]],

        [[1., 1.]]])
torch.Size([2, 1, 2])
---------------
tensor([[1., 1.],
        [1., 1.]])
torch.Size([2, 2])
---------------


In [30]:
#파이토치:토치를 쓰기위해 데이터 가공 해야함
#torch의 연결
t1=torch.tensor([1,2,3])
t2=torch.tensor([4,5,6])

torch.cat([t1, t2])

tensor([1, 2, 3, 4, 5, 6])

In [32]:
#Tensor의 수학함수 사용
t=torch.tensor([1.0,2.0,3.0])#수학함수 사용시 실수 기반으로 계산한다.
print(torch.sin(t))
print(torch.mean(t))
print(torch.sum(t))
print(t**2)

tensor([0.8415, 0.9093, 0.1411])
tensor(2.)
tensor(6.)
tensor([1., 4., 9.])


In [ ]:
#행렬곱셈=>파이토치:딥러닝
#행렬 곱셈
t1=torch.tensor(
[
    [1,2,3],
    [4,5,6]
]
)

t2=torch.tensor(
    [
        [7],
        [8],
        [9]
    ]
)#행렬곱셈 차원이 같아야함

print(torch.matmul(t1,t2))#matrix_mul
print(1*7+2*8+3*9)
print(4*7+5*8+6*9)

tensor([[ 50],
        [122]])
50
122


---
#DataSet(target&feature)과 DataLoader
-데이터의 전처리와 모델학습을 효율적으로 수행하기 위한 핵심 구성요소
-DataSet은 데이터와 라벨을 저장
-DataLoader는 이러한 데이터를 쉽게 순회 할수 있게 한다.
#epoch =>과대적합, 역전파시 순회(shuffle):골고루 학습:과대적합 방지

#DataSet과 DataLoader의 개념(역할)
#DataSet
-역할:데이터 샘플과 그에 해당하는 레이블을 저장
-주요 Method
 -init:데이터셋 초기화 및 데이터 로드
 -len:데이터셋의 샘플 갯수를 반환
 -getitem:주어진 인덱스에 해당하는 샘플을 반환(return)

#DataLoader
-역할:DataSet을 Batch단위로 쉽게 접근할수 있도록 하는 iterable 객체를 제공#연속=리스트
-주요 Method
 -batch_size:한번에 불러올 데이터의 크기
 -shuffle:데이터를 무작위로 섞을지 여부
 -num_workers:데이터를 로드할때 사용할 서브 프로세스의 수(LMM)

In [ ]:
#기본 데이터 셋 클래스 정의
from torch.utils.data import Dataset#기본 클래스
class SimpleDataset(Dataset):#상속:메소드=클라스 안 함수
    def __init__(self,data,labels):#생성자
        self.data=data
        self.labels=labels

    def __len__(self):
        return len(self.data)
    
    def __getitem__(self, idx):#__시스템에서 사용하는 변수
        return self.data[idx],self.labels[idx]

In [ ]:
data=[[1,2],
      [3,4],
      [5,6]]
labels=[0,1,0]

dataset=SimpleDataset(data,labels)

In [ ]:
print(dataset.data)
print(dataset.labels)
print(len(dataset))#인스턴스=객체, 리스트 아님
print(dataset[1])#get_item

[[1, 2], [3, 4], [5, 6]]
[0, 1, 0]
3
([3, 4], 1)


In [50]:
#기본 dataloader 사용:Shuffle하지 않고 전체를 한번에 사용하자 batch_size=3
from torch.utils.data import DataLoader
dataloader=DataLoader(dataset,batch_size=3,shuffle=False)
dataloader

for batch in dataloader:
    print(batch)#열중심&텐서로 바뀜

[[tensor([1, 3, 5]), tensor([2, 4, 6])], tensor([0, 1, 0])]


In [ ]:
#shuffle하고 2개씩 불러오기
dataloader=DataLoader(dataset,batch_size=2,shuffle=True)#true많이 씀
for batch in dataloader:
    print(batch)#2개=>나머지1개

[[tensor([3, 1]), tensor([4, 2])], tensor([1, 0])]
[[tensor([5]), tensor([6])], tensor([0])]
